version: '3'

services:
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_DB: $PSA_POSTGRES_DB
      POSTGRES_USER: $PSA_POSTGRES_USER
      POSTGRES_PASSWORD: $PSA_POSTGRES_PASSWORD

    ports:
    - $PSA_POSTGRES_PORT:5432

    volumes:
    - pgdata:/var/lib/postgresql/data:rw

  app:
    image:  openjdk:8-jre-alpine
    restart: always
    environment:
      PSA_POSTGRES_HOST: db
      PSA_POSTGRES_PORT: 5432
      PSA_POSTGRES_DB: $PSA_POSTGRES_DB
      PSA_POSTGRES_USER: $PSA_POSTGRES_USER
      PSA_POSTGRES_PASSWORD: $PSA_POSTGRES_PASSWORD

    working_dir: /app
    command: java -jar app.jar
    ports:
    - $PSA_APP_PORT:8080

    volumes:
    - $PSA_APP_JAR:/app/app.jar

    depends_on:
    - db

volumes:
  pgdata:
