spring:
  application:
    name: product-store-api

  liquibase:
    change-log: classpath:/db/changelog-master.xml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  profiles:
    active: prod
