-- liquibase formatted sql

-- changeset Isbel:1724434913481-1
CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    measure     VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (id)
);
CREATE TABLE shop
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    address     VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_shop PRIMARY KEY (id)
);
CREATE TABLE lot
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    received   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    amount     DOUBLE PRECISION                        NOT NULL,
    cost       DOUBLE PRECISION                        NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_lot PRIMARY KEY (id)
);
CREATE TABLE pack
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivered TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    amount    DOUBLE PRECISION                        NOT NULL,
    lot_id    BIGINT                                  NOT NULL,
    shop_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_pack PRIMARY KEY (id)
);
CREATE TABLE sale
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    registered TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    amount     DOUBLE PRECISION                        NOT NULL,
    price      DOUBLE PRECISION                        NOT NULL,
    pack_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_sale PRIMARY KEY (id)
);
ALTER TABLE product
    ADD CONSTRAINT uc_product_code UNIQUE (code);
ALTER TABLE lot
    ADD CONSTRAINT FK_LOT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);
ALTER TABLE pack
    ADD CONSTRAINT FK_PACK_ON_LOT FOREIGN KEY (lot_id) REFERENCES lot (id);
ALTER TABLE pack
    ADD CONSTRAINT FK_PACK_ON_SHOP FOREIGN KEY (shop_id) REFERENCES shop (id);
ALTER TABLE sale
    ADD CONSTRAINT FK_SALE_ON_PACK FOREIGN KEY (pack_id) REFERENCES pack (id);

